# Generated by Django 3.2.5 on 2021-08-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0026_delete_care'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('care_guide', models.TextField()),
                ('cage_setup', models.TextField()),
                ('lighting', models.TextField()),
                ('heating', models.TextField()),
                ('feeding_schedule', models.TextField()),
                ('known_problems', models.TextField()),
                ('other_information', models.TextField()),
                ('other_information_name', models.CharField(default='', max_length=30)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care', related_query_name='care', to='animals.animal')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.category')),
            ],
        ),
    ]
