# Generated by Django 3.2.5 on 2021-08-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_province',
            new_name='default_county',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_city',
            new_name='default_town_or_city',
        ),
    ]
