# Generated by Django 3.2.5 on 2021-07-11 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20210711_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.category'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='food',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='temperament',
            field=models.CharField(default='', max_length=50),
        ),
    ]
