# Generated by Django 3.2.5 on 2021-07-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20210711_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='friendly_name',
        ),
    ]
