# Generated by Django 3.2.5 on 2021-07-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_alter_animal_animal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animal_id',
        ),
    ]
