# Generated by Django 3.2.5 on 2021-07-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_remove_animal_animal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_id',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
