# Generated by Django 3.2.5 on 2021-07-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_animal_animal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
