# Generated by Django 3.2.5 on 2021-07-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0012_alter_animal_animal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='animal',
            name='lifespan',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='animal',
            name='max_length',
            field=models.CharField(default='', max_length=30),
        ),
    ]
