# Generated by Django 3.2.5 on 2021-07-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0013_auto_20210714_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='cage_setup',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='animal',
            name='care_guide',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='animal',
            name='feeding_schedule',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='animal',
            name='heating',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='animal',
            name='known_problems',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='animal',
            name='lighting',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='animal',
            name='other_information',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='animal',
            name='temperature',
            field=models.CharField(default='', max_length=30),
        ),
    ]
