# Generated by Django 3.2.5 on 2021-07-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0014_auto_20210717_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='cage_setup',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='care_guide',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='feeding_schedule',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='animal',
            name='known_problems',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='other_information',
            field=models.TextField(),
        ),
    ]
