# Generated by Django 3.2.5 on 2021-07-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0016_auto_20210717_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='other_information_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
