# Generated by Django 3.2.5 on 2021-07-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0017_animal_other_information_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
