# Generated by Django 3.2.5 on 2021-07-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0018_category_friendly_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='friendly_name',
        ),
    ]
