# Generated by Django 3.2.5 on 2021-07-27 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0019_remove_category_friendly_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_id', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('user', models.CharField(default='', max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('rating_out_of_five', models.IntegerField(default=0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', related_query_name='rating', to='animals.animal')),
            ],
        ),
    ]
