# Generated by Django 3.2.5 on 2021-07-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0020_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating_id',
        ),
    ]
