# Generated by Django 3.2.5 on 2021-07-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0021_remove_rating_rating_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rate_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
