# Generated by Django 3.2.5 on 2021-08-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0022_rating_rate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rate_id',
        ),
    ]
