# Generated by Django 3.2.5 on 2021-08-04 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0023_remove_rating_rate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='cage_setup',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='care_guide',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='feeding_schedule',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='heating',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='known_problems',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='lighting',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='other_information',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='other_information_name',
        ),
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_guide', models.TextField()),
                ('cage_setup', models.TextField()),
                ('lighting', models.TextField()),
                ('heating', models.TextField()),
                ('feeding_schedule', models.TextField()),
                ('known_problems', models.TextField()),
                ('other_information', models.TextField()),
                ('other_information_name', models.CharField(default='', max_length=30)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care', related_query_name='care', to='animals.animal')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.category')),
            ],
        ),
    ]
