# Generated by Django 3.2.5 on 2021-08-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0024_auto_20210804_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='care',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
