# Generated by Django 3.2.5 on 2021-08-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0025_care_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Care',
        ),
    ]
