# Generated by Django 3.2.5 on 2021-08-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0027_auto_20210811_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
